server:
  port: 7777
spring:
  application:
    name: loadbalance

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#client: #客户端 spring.application.name
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #对应的配置类 上面列表

##超时处理
#client: #客户端 spring.application.name
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #对应的配置类 上面列表
#    ConnectTimeout: 30000
#    ReadTimeout: 30000
#    MaxAutoRetries: 1 #对第一次请求的服务重试次数
#    MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
#    OkToRetryOnAllOperations: true #对所有操作请求都进行重试

##饥饿加载 进行客户端负载均衡时并不是启动时就加载上下文，而是在实际请求的时候才去创建，严重的时候
##会造成超时和重试
#ribbon:
#  eager-load:
#    enabled: true
#    clients: client #具体的应用名称

##脱离eureka
#ribbon:
#  eureka:
#    enabled: false
#client:
#    ribbon:
#      listOfServers: http://localhost:7070,http://localhost:7071