spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: service_v1
        uri: http://localhost:8001/v1
        predicates:
        - Path=/test
        - Weight=service, 95
      - id: service_v2
        uri: http://localhost:8001/v2
        predicates:
        - Path=/test
        - Weight=service, 5



server:
  port: 9000
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false